# Generated by Django 2.2.8 on 2020-02-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='borrowing',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
